version: '3.4'
services:
  db:
    restart: unless-stopped
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: 1234enter
    ports:
      - '5432:5432'
    volumes:
      - ./create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
  kecloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak:12.0.4
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - '8080:8080'
networks:
  production-network:
    driver: bridge